"""Initial

Revision ID: 3b2c0cbbfc9e
Revises: 75076844b9b1
Create Date: 2026-02-11 17:53:01.857390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2c0cbbfc9e'
down_revision: Union[str, Sequence[str], None] = '75076844b9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bites', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('cluster_data', sa.Column('temperature', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster_data', 'temperature')
    op.drop_column('bites', 'temperature')
    # ### end Alembic commands ###
