"""added elevation to Cluster

Revision ID: 572107ee2a2f
Revises: 9c23a54d756e
Create Date: 2026-02-28 20:16:56.305919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572107ee2a2f'
down_revision: Union[str, Sequence[str], None] = '9c23a54d756e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster_data', 'avg_elevation')
    op.add_column('clusters', sa.Column('elevation', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'elevation')
    op.add_column('cluster_data', sa.Column('avg_elevation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
