"""added status field to bite

Revision ID: 6fd22e53a187
Revises: 3b2c0cbbfc9e
Create Date: 2026-02-25 18:34:54.744635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd22e53a187'
down_revision: Union[str, Sequence[str], None] = '3b2c0cbbfc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    weather_status_enum = sa.Enum(
        'PENDING', 'SUCCESS', 'NO_STATION', 'NO_DATA', 'NO_DATE', 'NO_SNOW',
        'NO_TEMP', 'ERROR',
        name='bites_status_enum'
    )
    weather_status_enum.create(op.get_bind())

    roles_enum = sa.Enum('USER', 'ADMIN', name='role_enum')
    roles_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bites', sa.Column('weather_status', sa.Enum('PENDING', 'SUCCESS', 'NO_STATION', 'NO_DATA', 'NO_DATE', 'NO_SNOW', 'NO_TEMP', 'ERROR', name='bites_status_enum'), server_default='PENDING', nullable=False))
    op.drop_constraint(op.f('cluster_data_cluster_id_fkey'), 'cluster_data', type_='foreignkey')
    op.create_foreign_key(None, 'cluster_data', 'clusters', ['cluster_id'], ['id'])
    op.drop_constraint(op.f('clusters_region_id_fkey'), 'clusters', type_='foreignkey')
    op.create_foreign_key(None, 'clusters', 'regions', ['region_id'], ['id'])
    op.alter_column(
        'roles',
        'name',
        type_=roles_enum,
        existing_type=sa.VARCHAR(),
        nullable=False,
        postgresql_using="name::role_enum"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'roles',
        'name',
        type_=sa.VARCHAR(),
        existing_type=sa.Enum('USER', 'ADMIN', name='role_enum'),
        nullable=False,
        postgresql_using="name::VARCHAR"
    )
    roles_enum = sa.Enum('USER', 'ADMIN', name='role_enum')
    roles_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_constraint(None, 'clusters', type_='foreignkey')
    op.create_foreign_key(op.f('clusters_region_id_fkey'), 'clusters', 'regions', ['region_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'cluster_data', type_='foreignkey')
    op.create_foreign_key(op.f('cluster_data_cluster_id_fkey'), 'cluster_data', 'clusters', ['cluster_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('bites', 'weather_status')
    # ### end Alembic commands ###
