"""Initial

Revision ID: 75076844b9b1
Revises: 
Create Date: 2026-02-11 16:06:51.169522

"""
from typing import Sequence, Union
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75076844b9b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisements',
    sa.Column('target_URL', sa.String(), nullable=True),
    sa.Column('banner_URL', sa.String(), nullable=True),
    sa.Column('amount_of_clicks', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
#    op.create_index('idx_regions_boundary', 'regions', ['boundary'], unique=False, postgresql_using='gist')
    op.execute('CREATE INDEX IF NOT EXISTS idx_regions_boundary ON regions USING gist (boundary)')
    op.create_table('roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clusters',
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
#   op.create_index('idx_clusters_geometry', 'clusters', ['geometry'], unique=False, postgresql_using='gist')
    op.execute('CREATE INDEX IF NOT EXISTS idx_clusters_geometry ON clusters USING gist (geometry)')
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('bites',
    sa.Column('date_of_bite', sa.Date(), nullable=False),
    sa.Column('location_description', sa.String(), nullable=True),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('snow_depth', sa.Float(), nullable=True),
    sa.Column('point_of_bite', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('cluster_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
#    op.create_index('idx_bites_point_of_bite', 'bites', ['point_of_bite'], unique=False, postgresql_using='gist')
    op.execute('CREATE INDEX IF NOT EXISTS idx_bites_point_of_bite ON bites USING gist (point_of_bite)')
    op.create_table('cluster_data',
    sa.Column('amount_of_bites', sa.Integer(), nullable=False),
    sa.Column('predicted_amount_of_bites', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_elevation', sa.Float(), nullable=True),
    sa.Column('avg_snow_depth', sa.Float(), nullable=True),
    sa.Column('cluster_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cluster_data')
    op.drop_index('idx_bites_point_of_bite', table_name='bites', postgresql_using='gist')
    op.drop_table('bites')
    op.drop_table('user_roles')
    op.drop_index('idx_clusters_geometry', table_name='clusters', postgresql_using='gist')
    op.drop_table('clusters')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index('idx_regions_boundary', table_name='regions', postgresql_using='gist')
    op.drop_table('regions')
    op.drop_table('advertisements')
    # ### end Alembic commands ###
