"""deleted weather data from Bite

Revision ID: 9c23a54d756e
Revises: 6fd22e53a187
Create Date: 2026-02-28 19:30:57.818007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c23a54d756e'
down_revision: Union[str, Sequence[str], None] = '6fd22e53a187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bites', 'snow_depth')
    op.drop_column('bites', 'elevation')
    op.drop_column('bites', 'temperature')
    op.drop_column('bites', 'weather_status')
    op.drop_index(op.f('uq_cluster_date'), table_name='cluster_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_cluster_date'), 'cluster_data', ['cluster_id', 'date'], unique=True)
    op.add_column('bites', sa.Column('weather_status', postgresql.ENUM('PENDING', 'SUCCESS', 'NO_STATION', 'NO_DATA', 'NO_DATE', 'NO_SNOW', 'NO_TEMP', 'ERROR', name='bites_status_enum'), server_default=sa.text("'PENDING'::bites_status_enum"), autoincrement=False, nullable=False))
    op.add_column('bites', sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('bites', sa.Column('elevation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('bites', sa.Column('snow_depth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
