"""(((((

Revision ID: a932b7b5a377
Revises: feb591d604c4
Create Date: 2026-03-14 16:11:41.893755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a932b7b5a377'
down_revision: Union[str, Sequence[str], None] = 'feb591d604c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bites', sa.Column('region_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'bites', 'regions', ['region_id'], ['id'])
    op.alter_column('clusters', 'centroid',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               nullable=False)
    op.drop_index(op.f('idx_cluster_region'), table_name='clusters')
    op.create_index('idx_clusters_centroid', 'clusters', ['centroid'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_clusters_centroid', table_name='clusters', postgresql_using='gist')
    op.create_index(op.f('idx_cluster_region'), 'clusters', ['region_id'], unique=False)
    op.alter_column('clusters', 'centroid',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               nullable=True)
    op.drop_constraint(None, 'bites', type_='foreignkey')
    op.drop_column('bites', 'region_id')
    # ### end Alembic commands ###
