"""added weather_status to Cluster_data

Revision ID: c2fc3a811bad
Revises: 572107ee2a2f
Create Date: 2026-02-28 22:14:24.857176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2fc3a811bad'
down_revision: Union[str, Sequence[str], None] = '572107ee2a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_data', sa.Column('weather_status', sa.Enum('PENDING', 'SUCCESS', 'NO_STATION', 'NO_DATA', 'NO_DATE', 'NO_SNOW', 'NO_TEMP', 'ERROR', name='bites_status_enum'), server_default='PENDING', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster_data', 'weather_status')
    # ### end Alembic commands ###
